apiVersion: hub.mydecisive.ai/v1
kind: MdaiDal
metadata:
  namespace: mdai
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaidal-sample
spec:
  aws:
    region: us-east-1
    credentials: {}
  s3:
    bucket: telemetry
  imageSpec: {}

  granularity: hourly
  marshaler: json
  usePayloadTs: false
